### ISSUE TITLE
Error with procps 3.2.8 on Centos 6.9

### ISSUE THREAD

**Issue by dawookie** [rendicott/check_mem#5]
Centos 6.9 ships using procps-3.2.8.  The version output splits into 3 tokens not 4.

Using the last token instead of a specifically number token will work with procps-3.2.x as well as procps-ng-3.3.x.

I will submit a pull request with a proposed fix that I tested with procps-ng 3.3.9 and procps 3.2.8

**Comment by rendicott** [comment]
Cool. I'll be on the lookout for the P.R.

**Comment by dawookie** [comment]
Thank you sir
